version: '2'

networks:
  default-network:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
    networks:
      - default-network

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql
    container_name: market_api_symfony_php_fpm
    networks:
      - default-network

  pgsql:
    image: postgres:11.3
    ports:
      - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./persistent_data/pgsql:/var/lib/postgresql/data
    networks:
      - default-network

  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - ./persistent_data/zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default-network

  kafka:
    image: bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - ./persistent_data/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - default-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - default-network
